In [55]:
# Load libs
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn
import altair as alt

In [56]:
# Load People.csv, FieldingPost.csv, PitchingPost.csv, BattingPost.csv, Schools.csv, Salaries.csv
DATA_PATH = "baseball/core/"
ppl  = pd.read_csv(DATA_PATH + "People.csv")
fld  = pd.read_csv(DATA_PATH + "FieldingPost.csv")
pch  = pd.read_csv(DATA_PATH + "PitchingPost.csv")
bat  = pd.read_csv(DATA_PATH + "BattingPost.csv")
scl  = pd.read_csv(DATA_PATH + "Schools.csv")
sal  = pd.read_csv(DATA_PATH + "Salaries.csv")
col  = pd.read_csv(DATA_PATH + "CollegePlaying.csv")
infCoef = pd.read_csv("baseball/infCoef.csv")

In [57]:
# "Clean" data
fld.drop(['CS','SB','PB'], axis="columns", inplace=True)
ppl.drop(['birthMonth','birthDay','birthCountry',
       'birthState','birthCity','deathYear','deathMonth','deathDay',
       'deathCountry','deathState','deathCity'], axis="columns", inplace=True)
ppl['finalGame'] = ppl.finalGame.astype('datetime64[ns]')
ppl = ppl[ppl.finalGame.dt.year > 1900] # modern baseball rules established in 1901
sal = sal[sal.yearID > 1900]

# Join data
college = col.merge(scl, on='schoolID', how='left').iloc[:, :-1]

In [ ]:
last_college = college.groupby('playerID').max()
last_college.reset_index(inplace=True)

In [ ]:
# NOTE: Something to think about is that ivy prestige is not the same as sport prestige 
# i.e. LSU, Texas USC Miami ASU Cal State Fullerton and oregon
sorta_ivy = ['Brown University','Columbia University', 'Cornell University',
             'Dartmouth College','Harvard University','University of Pennsylvania',
             'Princeton University','Yale University','Vanderbilt University',
             'Duke University','Rice University']
prestige = last_college[last_college.name_full.isin(sorta_ivy)]
prestige[prestige.yearID > 1984]

,playerID,schoolID,yearID,name_full,city,state
0,aardsda01,rice,2003,Rice University,State College,TX
32,adkinst01,upenn,1986,University of Pennsylvania,Philadelphia,PA
89,alvarpe01,vandy,2008,Vanderbilt University,Nashville,TN
115,anderma01,rice,1997,Rice University,Houston,TX
308,barziph01,txalvin,2001,Rice University,Houston,TX
...,...,...,...,...,...,...
5714,stromma01,duke,2012,Duke University,Durham,NC
5967,trombmi01,duke,1989,Duke University,Durham,NC
6057,venabwi01,princeton,2005,Princeton University,Princeton,NJ
6529,youngch03,princeton,2000,Princeton University,Princeton,NJ
6553,zeidjo01,vandy,2009,Vanderbilt University,New Orleans,TN

In [62]:
last_college[last_college.yearID > 1984]

,playerID,schoolID,yearID,name_full,city,state
0,aardsda01,rice,2003,Rice University,State College,TX
1,abadan01,gamiddl,1993,Middle Georgia College,Cochran,GA
3,abbotje01,kentucky,1994,University of Kentucky,Lexington,KY
4,abbotji01,michigan,1988,University of Michigan,Ann Arbor,MI
5,abbotky01,ucsd,1989,"University of California, San Diego",Long Beach,CA
...,...,...,...,...,...,...
6569,zoccope01,rutgers,1999,"Rutgers, the State University of New Jersey",New Brunswick,NJ
6570,zoskyed01,fresnost,1989,California State University Fresno,Fresno,CA
6571,zuberjo01,california,1992,"University of California, Berkeley",Berkeley,CA
6572,zuninmi01,florida,2012,University of Florida,Gainesville,FL
6573,zupcibo01,oralrob,1987,Oral Roberts University,Tulsa,OK

In [ ]:
# Look at

In [ ]:
# Look at salary overtime 
# Apply coef on everyones salary
sal = sal.merge(infCoef, on="yearID", how="left")
sal["finalSalary"] = sal.coefficient * sal.salary
# 
stat_sal = pd.DataFrame()
# Take the avg
stat_sal['mean']   = sal.groupby("yearID")["finalSalary"].mean()
stat_sal['median'] = sal.groupby("yearID")["finalSalary"].median()
stat_sal['lower']  = sal.groupby("yearID")["finalSalary"].quantile(0.25)
stat_sal['higher'] = sal.groupby("yearID")["finalSalary"].quantile(0.75)
stat_sal.reset_index(inplace=True)
stat_sal = stat_sal.melt(id_vars="yearID")


# NOTE: Salary only starts at 1985 (womp-womp)
# Plot trend
sal_chart = alt.Chart(stat_sal).mark_line(interpolate="monotone").encode(
    x="yearID:Q",
    y="value:Q",
    color="variable:N"
)

In [ ]:
'''
Talking points:
- mean higher than 75th percentile
- All have a positive increase, even 25 percentile
- TODO: Plot highest salary for each year
'''
sal_chart.show()

alt.Chart(...)

In [52]:
last_college

,schoolID,yearID,name_full,city,state
playerID,,,,,
aardsda01,rice,2003,Rice University,State College,TX
abadan01,gamiddl,1993,Middle Georgia College,Cochran,GA
abbeybe01,vermont,1892,University of Vermont,Burlington,VT
abbotje01,kentucky,1994,University of Kentucky,Lexington,KY
abbotji01,michigan,1988,University of Michigan,Ann Arbor,MI
...,...,...,...,...,...
zoskyed01,fresnost,1989,California State University Fresno,Fresno,CA
zuberjo01,california,1992,"University of California, Berkeley",Berkeley,CA
zuninmi01,florida,2012,University of Florida,Gainesville,FL
zupcibo01,oralrob,1987,Oral Roberts University,Tulsa,OK
zuvelpa01,stanford,1980,Stanford University,Palo Alto,CA

### Questions to Study

school vs salary

number of appearances vs salary (sweet spot?)